---

- include_vars: main.yml

- name: install apache
  apt: 
    name: apache2
    state: present 
    
- name: install apache2_packages
  apt: 
    name: "{{ item }}"
    state: present 
  with_items: "{{ apache2_packages }}"
